# db-service/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: stock-project
spec:
  selector:
    app: db-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
